# Example Home Assistant configuration with Kubernetes integration
# Copy this to your configuration.yaml and customize as needed

# Home Assistant configuration
homeassistant:
  name: My Home
  latitude: 37.7749
  longitude: -122.4194
  elevation: 0
  unit_system: metric
  time_zone: America/Los_Angeles

# Enable logging for debugging
logger:
  default: info
  logs:
    custom_components.kubernetes: debug

# HTTP configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Frontend configuration
frontend:

# API configuration
api:

# Configuration for the Kubernetes integration
# This will be configured through the UI, but here's an example of what it looks like:
# kubernetes:
#   - name: "Production Cluster"
#     host: "k8s-prod.example.com"
#     port: 6443
#     cluster_name: "production"
#     namespace: "default"
#     api_token: "your-api-token-here"
#     verify_ssl: true

# Example configuration.yaml entry for Kubernetes integration
kubernetes:
  host: "https://your-k8s-cluster:6443"
  api_token: "your-api-token"
  ca_cert: "your-ca-cert"
  cluster_name: "production"
  namespace: "default"
  monitor_all_namespaces: false

# Example automations using the new multi-selection services

# Stop multiple deployments at once
automation:
  - alias: "Stop Multiple Deployments"
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - service: kubernetes.stop_deployment
        data:
          deployment_names:
            - "web-app"
            - "api-server"
            - "cache-service"
          namespace: "production"

  # Start multiple deployments with specific replica counts
  - alias: "Start Multiple Deployments"
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: kubernetes.start_deployment
        data:
          deployment_names:
            - "web-app"
            - "api-server"
          replicas: 3
          namespace: "production"

  # Scale multiple StatefulSets
  - alias: "Scale Multiple StatefulSets"
    trigger:
      platform: time
      at: "08:00:00"
    action:
      - service: kubernetes.scale_statefulset
        data:
          statefulset_names:
            - "database-primary"
            - "database-replica"
          replicas: 2
          namespace: "database"

  # Single deployment operations (backward compatible)
  - alias: "Stop Single Deployment"
    trigger:
      platform: time
      at: "23:00:00"
    action:
      - service: kubernetes.stop_deployment
        data:
          deployment_name: "monitoring"
          namespace: "monitoring"

  # Multiple StatefulSets with different replica counts (requires multiple calls)
  - alias: "Scale Different StatefulSets"
    trigger:
      platform: time
      at: "09:00:00"
    action:
      - service: kubernetes.scale_statefulset
        data:
          statefulset_names:
            - "redis-cache"
            - "redis-session"
          replicas: 3
          namespace: "cache"
      - service: kubernetes.scale_statefulset
        data:
          statefulset_names:
            - "elasticsearch-data"
            - "elasticsearch-master"
          replicas: 1
          namespace: "logging"

# Example scripts for manual control
script:
  kubernetes_status_check:
    alias: "Check Kubernetes Status"
    sequence:
      - service: homeassistant.update_entity
        target:
          entity_id:
            - sensor.kubernetes_pods_count
            - sensor.kubernetes_nodes_count

            - sensor.kubernetes_deployments_count
            - binary_sensor.kubernetes_cluster_health

  scale_production_api:
    alias: "Scale Production API"
    sequence:
      - service: kubernetes.scale_deployment
        data:
          deployment_name: production-api
          replicas: 3
          namespace: production

  stop_development:
    alias: "Stop Development Environment"
    sequence:
      - service: kubernetes.stop_deployment
        data:
          deployment_name: development-api
          namespace: development
      - service: kubernetes.stop_deployment
        data:
          deployment_name: development-database
          namespace: development
      - service: notify.mobile_app
        data:
          title: "Development Environment"
          message: "Development environment has been stopped"

  start_development:
    alias: "Start Development Environment"
    sequence:
      - service: kubernetes.start_deployment
        data:
          deployment_name: development-api
          replicas: 1
          namespace: development
      - service: kubernetes.start_deployment
        data:
          deployment_name: development-database
          replicas: 1
          namespace: development
      - service: notify.mobile_app
        data:
          title: "Development Environment"
          message: "Development environment has been started"

  scale_production_databases:
    alias: "Scale Production Databases"
    sequence:
      - service: kubernetes.scale_statefulset
        data:
          statefulset_name: redis-cache
          replicas: 3
          namespace: production
      - service: kubernetes.scale_statefulset
        data:
          statefulset_name: postgres-db
          replicas: 2
          namespace: production

  stop_production_databases:
    alias: "Stop Production Databases"
    sequence:
      - service: kubernetes.stop_statefulset
        data:
          statefulset_name: redis-cache
          namespace: production
      - service: kubernetes.stop_statefulset
        data:
          statefulset_name: postgres-db
          namespace: production
      - service: notify.mobile_app
        data:
          title: "Production Databases"
          message: "Production databases have been stopped"

# Example scenes
scene:
  kubernetes_dashboard:
    name: "Kubernetes Dashboard"
    entities:
      sensor.kubernetes_pods_count:
        state: "0"
      sensor.kubernetes_nodes_count:
        state: "0"

      sensor.kubernetes_deployments_count:
        state: "0"
      sensor.kubernetes_statefulsets_count:
        state: "0"
      binary_sensor.kubernetes_cluster_health:
        state: "off"

  production_mode:
    name: "Production Mode"
    entities:
      sensor.kubernetes_pods_count:
        state: "50"
      sensor.kubernetes_deployments_count:
        state: "10"
      sensor.kubernetes_statefulsets_count:
        state: "3"

  development_mode:
    name: "Development Mode"
    entities:
      sensor.kubernetes_pods_count:
        state: "5"
      sensor.kubernetes_deployments_count:
        state: "3"
      sensor.kubernetes_statefulsets_count:
        state: "1"

# Lovelace dashboard configuration (optional)
# This creates a dedicated dashboard for Kubernetes monitoring and control
lovelace:
  mode: yaml
  dashboards:
    kubernetes:
      title: "Kubernetes Monitoring & Control"
      icon: mdi:kubernetes
      show_in_sidebar: true
      path: kubernetes
      badges: []
      cards:
        - type: vertical-stack
          title: "Kubernetes Cluster Status"
          cards:
            - type: entities
              title: "Cluster Health"
              entities:
                - entity: binary_sensor.kubernetes_cluster_health
            - type: entities
              title: "Resource Counts"
              entities:
                - entity: sensor.kubernetes_pods_count
                - entity: sensor.kubernetes_nodes_count

                - entity: sensor.kubernetes_deployments_count
                - entity: sensor.kubernetes_statefulsets_count
        - type: vertical-stack
          title: "Deployment Control"
          cards:
            - type: entities
              title: "Production Deployments"
              entities:
                - entity: switch.production_api_deployment
                - entity: switch.api_gateway_deployment
            - type: entities
              title: "Development Deployments"
              entities:
                - entity: switch.development_api_deployment
                - entity: switch.development_database_deployment
        - type: vertical-stack
          title: "StatefulSet Control"
          cards:
            - type: entities
              title: "Production StatefulSets"
              entities:
                - entity: switch.redis_cache_statefulset
                - entity: switch.postgres_db_statefulset
            - type: entities
              title: "Development StatefulSets"
              entities:
                - entity: switch.development_redis_statefulset
        - type: vertical-stack
          title: "Quick Actions"
          cards:
            - type: button
              name: "Scale Production API"
              tap_action:
                action: call-service
                service: script.scale_production_api
            - type: button
              name: "Stop Development"
              tap_action:
                action: call-service
                service: script.stop_development
            - type: button
              name: "Start Development"
              tap_action:
                action: call-service
                service: script.start_development
            - type: button
              name: "Scale Production Databases"
              tap_action:
                action: call-service
                service: script.scale_production_databases
            - type: button
              name: "Stop Production Databases"
              tap_action:
                action: call-service
                service: script.stop_production_databases
